library(msigdbr)
library(Seurat)
# obj_neu <- subset(obj_seurat, subset = celltype == "Neu")
obj_seurat <- readRDS("/path/to/obj_neu.rds")
# C5 -- GO:BP
gmt <- msigdbr(species = "Homo sapiens", category = "C5", subcategory = "GO:BP")
gmt <- unique(gmt[,c("gs_name","gene_symbol")])
colnames(gmt) <- c("term","gene")
gmt$term <- tolower(gmt$term)
geneSets <- lapply(unique(gmt$term),function(x){gmt$gene[gmt$term==x]})
names(geneSets) <- unique(gmt$term)
obj_seurat <- AddModuleScore(object = obj_seurat, features = gmt)

# obj_tnk <- subset(obj_seurat, subset = celltype == "T_NK")
obj_seurat <- readRDS("/path/to/obj_tnk.rds")
# C5 -- GO:BP
gmt <- msigdbr(species = "Homo sapiens", category = "C5", subcategory = "GO:BP")
gmt <- unique(gmt[,c("gs_name","gene_symbol")])
colnames(gmt) <- c("term","gene")
gmt$term <- tolower(gmt$term)
geneSets <- lapply(unique(gmt$term),function(x){gmt$gene[gmt$term==x]})
names(geneSets) <- unique(gmt$term)
obj_seurat <- AddModuleScore(object = obj_seurat, features = gmt)
