# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: ubuntu-check

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-check-on-ubuntu:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        r-version: ['4.1.3']

    steps:
      - uses: actions/checkout@v3
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "knitr", "Seurat", "circlize", "heatmaply", "networkD3", "viridis", "ggplot2", "progress", "reshape2", "reshape2", "igraph", "crayon", "scales", "ggraph", "rmarkdown", "prettydoc", "correlation"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
